url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kim Dohoon" # the name of your site, e.g. ACME Corp.
description: "Data Scientist"
updates_limit: 5

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:slug

# Publications
publications:
  enabled: false

# Resume / CV link (only URL)
resume:
  url: https://drive.google.com/file/d/1SkWtu1H9wKOFWpnm7WIzMehkJOJuX_-T/view